import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import { Montserrat } from "next/font/google";
import { SBHeader } from "@/components/sb-header";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body
        className={` antialiased`}
      >
        <SBHeader />
        <main className="pt-20 md:pt-25 lg:pt-26.75 px-4 max-w-7xl mx-auto">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
